import Head from "next/head";
import { Inter } from "@next/font/google";
import {
   Chart as ChartJS,
   CategoryScale,
   LinearScale,
   PointElement,
   LineElement,
   Title,
   Tooltip,
   Legend,
} from "chart.js";
import { Line } from "react-chartjs-2";
import { faker } from "@faker-js/faker";

ChartJS.register(
   CategoryScale,
   LinearScale,
   PointElement,
   LineElement,
   Title,
   Tooltip,
   Legend
);

export const options = {
   animations: false,
   responsive: true,
   plugins: {
      legend: {
         position: "bottom" as const,
      },
   },
};
const labels = ["12:00", "12:01", "12:02", "12:03", "12:04", "12:05"];

export const data = {
   labels,
   datasets: [
      {
         label: "Node 1",
         data: [22, 20, 20, 20.2, 20.3, 20],
         borderColor: "rgb(255, 99, 132)/10",
         backgroundColor: "#000",
      },
      {
         label: "Node 2",
         data: [20, 19, 19.8, 20.2, 20.3, 20],
         borderColor: "blue",
         backgroundColor: "blue",
      },
      {
         label: "Node 3",
         data: [18, 19, 20.5, 21.2, 19.3, 20],
         borderColor: "red",
         backgroundColor: "red",
      },
      {
         label: "Node 4",
         data: [19, 19, 20, 22.2, 17.3, 23],
         borderColor: "green",
         backgroundColor: "green",
      },
      {
         label: "Node 5",
         data: [19, 19, 20, 23.2, 17.3, 23],
         borderColor: "orange",
         backgroundColor: "orange",
      },
   ],
};

const data2 = [
   {
      nodeId: 1,
      logs: [
         {
            logId: 1,
            temp: 30,
            pressure: 40,
            humidity: 20,
         },

         {
            logId: 2,
            temp: 30,
            pressure: 40,
            humidity: 20,
         },
         {
            logId: 3,
            temp: 30,
            pressure: 40,
            humidity: 20,
         },
         {
            logId: 4,
            temp: 20,
            pressure: 17,
            humidity: 37,
         },
         {
            logId: 5,
            temp: 30,
            pressure: 40,
            humidity: 20,
         },
         {
            logId: 6,
            temp: 30,
            pressure: 40,
            humidity: 20,
         },
         {
            logId: 7,
            temp: 30,
            pressure: 40,
            humidity: 20,
         },
      ],
   },
];

export default function Home() {
   const lastUpdated = new Date().toString();

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main
            style={{
               background: "white",
               minHeight: "100vh",
               width: "100vw",
               height: "100%",
            }}
         >
            <div className="flex w-full bg-white justify-between px-4 border-b-2">
               <div className="text-black py-4">
                  <div className="font-medium text-lg bg-white inline px-2 py-2 rounded-md">
                     Kathmandu - Smart lifevests v1.0
                  </div>
               </div>
               <div className="text-black  flex items-center">
                  <div>Modus:</div>
                  <div className="bg-white px-2 py-2 rounded-md space-x-2">
                     <div className="font-semibold text-md bg-gray-100 py-2 px-3 text-black inline rounded-md border-gray-300 border-2">
                        Overview
                     </div>
                     <div className="font-medium text-md bg-gray-100 py-2 px-3 text-black inline rounded-md">
                        Live
                     </div>
                  </div>
               </div>
            </div>

            <div className="px-6">
               <dl className="grid grid-cols-1 gap-5 sm:grid-cols-3 mt-12">
                  <div
                     key="0"
                     className="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6"
                  >
                     <dt className="truncate text-sm font-medium text-gray-500">
                        Lifevests
                     </dt>
                     <dd className="mt-1 text-3xl font-semibold tracking-tight text-gray-900">
                        20
                     </dd>
                  </div>
                  <div
                     key="1"
                     className="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6"
                  >
                     <dt className="truncate text-sm font-medium text-gray-500">
                        Recieved alerts (last 1 hour)
                     </dt>
                     <dd className="mt-1 text-3xl font-semibold tracking-tight text-red-500">
                        20
                     </dd>
                  </div>
                  <div
                     key="2"
                     className="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6"
                  >
                     <dt className="truncate text-sm font-medium text-gray-500">
                        Last updated
                     </dt>
                     <dd className="mt-1 text-md font-semibold tracking-tight text-gray-900">
                        <span>{lastUpdated.toString()}</span>
                     </dd>
                  </div>
               </dl>
               <hr className="mt-16 mb-16" />
               <h1 className="text-black font-medium text-xl text-left mt-5 mb-3">
                  Temperature per lifejacket
               </h1>
               <Line height={100} options={options} data={data} />;
               <hr className="mt-16 mb-16" />
               <h1 className="text-black font-medium text-xl text-left mt-5 mb-3">
                  Humidity per lifejacket
               </h1>
               <Line height={100} options={options} data={data} />;
               <hr />
            </div>
         </main>
      </>
   );
}
